package com.yycloud.core.beans;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table WIFI_CAMERA.
 */
public class WifiCamera {

    private Long id;
    private int device_addr;
    private String sn;
    private String name;
    private String username;
    private String password;

    public WifiCamera() {
    }

    public WifiCamera(Long id) {
        this.id = id;
    }

    public WifiCamera(Long id, int i, String sn, String name, String username, String password) {
        this.id = id;
        this.device_addr = i;
        this.sn = sn;
        this.name = name;
        this.username = username;
        this.password = password;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getDevice_addr() {
        return device_addr;
    }

    public void setDevice_addr(int device_addr) {
        this.device_addr = device_addr;
    }

    public String getSn() {
        return sn;
    }

    public void setSn(String sn) {
        this.sn = sn;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}
