package cn.yyshed.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import cn.yyshed.dao.DBShedStrategy;
import cn.yyshed.dao.DBAlarmEvent;
import cn.yyshed.dao.DBAlarmStrategyDefault;
import cn.yyshed.dao.DBAlarmStrategyCustom;

import cn.yyshed.dao.DBShedStrategyDao;
import cn.yyshed.dao.DBAlarmEventDao;
import cn.yyshed.dao.DBAlarmStrategyDefaultDao;
import cn.yyshed.dao.DBAlarmStrategyCustomDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBShedStrategyDaoConfig;
    private final DaoConfig dBAlarmEventDaoConfig;
    private final DaoConfig dBAlarmStrategyDefaultDaoConfig;
    private final DaoConfig dBAlarmStrategyCustomDaoConfig;

    private final DBShedStrategyDao dBShedStrategyDao;
    private final DBAlarmEventDao dBAlarmEventDao;
    private final DBAlarmStrategyDefaultDao dBAlarmStrategyDefaultDao;
    private final DBAlarmStrategyCustomDao dBAlarmStrategyCustomDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBShedStrategyDaoConfig = daoConfigMap.get(DBShedStrategyDao.class).clone();
        dBShedStrategyDaoConfig.initIdentityScope(type);

        dBAlarmEventDaoConfig = daoConfigMap.get(DBAlarmEventDao.class).clone();
        dBAlarmEventDaoConfig.initIdentityScope(type);

        dBAlarmStrategyDefaultDaoConfig = daoConfigMap.get(DBAlarmStrategyDefaultDao.class).clone();
        dBAlarmStrategyDefaultDaoConfig.initIdentityScope(type);

        dBAlarmStrategyCustomDaoConfig = daoConfigMap.get(DBAlarmStrategyCustomDao.class).clone();
        dBAlarmStrategyCustomDaoConfig.initIdentityScope(type);

        dBShedStrategyDao = new DBShedStrategyDao(dBShedStrategyDaoConfig, this);
        dBAlarmEventDao = new DBAlarmEventDao(dBAlarmEventDaoConfig, this);
        dBAlarmStrategyDefaultDao = new DBAlarmStrategyDefaultDao(dBAlarmStrategyDefaultDaoConfig, this);
        dBAlarmStrategyCustomDao = new DBAlarmStrategyCustomDao(dBAlarmStrategyCustomDaoConfig, this);

        registerDao(DBShedStrategy.class, dBShedStrategyDao);
        registerDao(DBAlarmEvent.class, dBAlarmEventDao);
        registerDao(DBAlarmStrategyDefault.class, dBAlarmStrategyDefaultDao);
        registerDao(DBAlarmStrategyCustom.class, dBAlarmStrategyCustomDao);
    }
    
    public void clear() {
        dBShedStrategyDaoConfig.getIdentityScope().clear();
        dBAlarmEventDaoConfig.getIdentityScope().clear();
        dBAlarmStrategyDefaultDaoConfig.getIdentityScope().clear();
        dBAlarmStrategyCustomDaoConfig.getIdentityScope().clear();
    }

    public DBShedStrategyDao getDBShedStrategyDao() {
        return dBShedStrategyDao;
    }

    public DBAlarmEventDao getDBAlarmEventDao() {
        return dBAlarmEventDao;
    }

    public DBAlarmStrategyDefaultDao getDBAlarmStrategyDefaultDao() {
        return dBAlarmStrategyDefaultDao;
    }

    public DBAlarmStrategyCustomDao getDBAlarmStrategyCustomDao() {
        return dBAlarmStrategyCustomDao;
    }

}
