package cn.yyshed.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DBALARM_EVENT.
 */
public class DBAlarmEvent {

    private Long id;
    private String event_id;
    private java.util.Date event_date;
    private String event_level;
    private String event_type;
    private String event_name;
    private Byte beread;
    private String event_state;
    private String detail;
    private java.util.Date createdAt;
    private java.util.Date updatedAt;
    private String user_name;
    private String smartgate_sn;
    private String smartgate_name;
    private String device_sn;
    private String sn;

    public DBAlarmEvent() {
    }

    public DBAlarmEvent(Long id) {
        this.id = id;
    }

    public DBAlarmEvent(Long id, String event_id, java.util.Date event_date, String event_level, String event_type, String event_name, Byte beread, String event_state, String detail, java.util.Date createdAt, java.util.Date updatedAt, String user_name, String smartgate_sn, String smartgate_name, String device_sn, String sn) {
        this.id = id;
        this.event_id = event_id;
        this.event_date = event_date;
        this.event_level = event_level;
        this.event_type = event_type;
        this.event_name = event_name;
        this.beread = beread;
        this.event_state = event_state;
        this.detail = detail;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.user_name = user_name;
        this.smartgate_sn = smartgate_sn;
        this.smartgate_name = smartgate_name;
        this.device_sn = device_sn;
        this.sn = sn;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEvent_id() {
        return event_id;
    }

    public void setEvent_id(String event_id) {
        this.event_id = event_id;
    }

    public java.util.Date getEvent_date() {
        return event_date;
    }

    public void setEvent_date(java.util.Date event_date) {
        this.event_date = event_date;
    }

    public String getEvent_level() {
        return event_level;
    }

    public void setEvent_level(String event_level) {
        this.event_level = event_level;
    }

    public String getEvent_type() {
        return event_type;
    }

    public void setEvent_type(String event_type) {
        this.event_type = event_type;
    }

    public String getEvent_name() {
        return event_name;
    }

    public void setEvent_name(String event_name) {
        this.event_name = event_name;
    }

    public Byte getBeread() {
        return beread;
    }

    public void setBeread(Byte beread) {
        this.beread = beread;
    }

    public String getEvent_state() {
        return event_state;
    }

    public void setEvent_state(String event_state) {
        this.event_state = event_state;
    }

    public String getDetail() {
        return detail;
    }

    public void setDetail(String detail) {
        this.detail = detail;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getUser_name() {
        return user_name;
    }

    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

    public String getSmartgate_sn() {
        return smartgate_sn;
    }

    public void setSmartgate_sn(String smartgate_sn) {
        this.smartgate_sn = smartgate_sn;
    }

    public String getSmartgate_name() {
        return smartgate_name;
    }

    public void setSmartgate_name(String smartgate_name) {
        this.smartgate_name = smartgate_name;
    }
    
    public String getDevice_sn() {
        return device_sn;
    }

    public void setDevice_sn(String device_sn) {
        this.device_sn = device_sn;
    }

    public String getSn() {
        return sn;
    }

    public void setSn(String sn) {
        this.sn = sn;
    }

}
