package cn.yyshed.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DBSHED_STRATEGY.
 */
public class DBShedStrategy {

    private String shed_id;
    private String strategy_type;
    private String content;

    public DBShedStrategy() {
    }

    public DBShedStrategy(String shed_id, String strategy_type, String content) {
        this.shed_id = shed_id;
        this.strategy_type = strategy_type;
        this.content = content;
    }

    public String getShed_id() {
        return shed_id;
    }

    public void setShed_id(String shed_id) {
        this.shed_id = shed_id;
    }

    public String getStrategy_type() {
        return strategy_type;
    }

    public void setStrategy_type(String strategy_type) {
        this.strategy_type = strategy_type;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

}
